import { useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../context/AuthContext";
import type { User } from "../types";
import { Notice } from "../components/Feedback";
const destination = (role: User["role"]) => role === "ADMIN" ? "/admin" : role === "STORE_OWNER" ? "/owner" : "/stores";
export function Login() { const navigate = useNavigate(); const { login } = useAuth(); const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); try { const data = await api<{token:string;user:User}>("/auth/login", { method:"POST", body:JSON.stringify({email:form.get("email"), password:form.get("password")}) }); login(data.token, data.user); navigate(destination(data.user.role)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in."); } }; return <AuthFrame title="Welcome back" subtitle="Sign in to manage the ratings that matter."><form onSubmit={submit}><label>Email<input name="email" type="email" required placeholder="you@company.com" /></label><label>Password<input name="password" type="password" required placeholder="Your password" /></label>{error && <Notice message={error}/>}<button className="button full">Sign in</button></form><p className="auth-switch">New to StorePulse? <Link to="/signup">Create a member account</Link></p></AuthFrame>; }
export function Signup() { const navigate = useNavigate(); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError(""); const f=new FormData(e.currentTarget);try{await api("/auth/signup",{method:"POST",body:JSON.stringify({name:f.get("name"),email:f.get("email"),address:f.get("address"),password:f.get("password")})});setSuccess("Member account created. You can sign in now.");setTimeout(()=>navigate("/login"),900)}catch(err){setError(err instanceof Error?err.message:"Unable to create account.")}};return <AuthFrame title="Start rating better" subtitle="Create a member account to discover and rate stores."><section className="role-explainer" aria-label="Account types"><div className="role-choice active"><strong>Member</strong><span>Sign up and rate stores</span></div><div className="role-choice"><strong>Store owner</strong><span>Created by an administrator with a store</span></div><div className="role-choice"><strong>Administrator</strong><span>Created by an existing administrator</span></div></section><p className="role-note">For account safety, public registration is available only for members. Store owner and administrator accounts must be provisioned by an administrator.</p><form onSubmit={submit}><label>Full name <small>Please enter your complete name; add your middle name if needed.</small><input name="name" minLength={20} maxLength={60} required placeholder="For example: Vedika Anil Sardeshmukh" title="Please enter your complete full name. Add your middle name if needed." /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Address<textarea name="address" maxLength={400} required placeholder="City, street, or full address" /></label><label>Password <small>8–16 chars, uppercase + special character</small><input name="password" type="password" minLength={8} maxLength={16} required placeholder="Example: Welcome!1" /></label>{error&&<Notice message={error}/>} {success&&<Notice type="success" message={success}/>}<button className="button full">Create member account</button></form><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></AuthFrame>}
function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <div className="auth-page"><section className="auth-intro"><div className="brand"><span>✦</span> StorePulse</div><h1>Clear ratings.<br/>Better choices.</h1><p>One focused workspace for customers, store owners, and platform teams.</p><div className="feature-list"><span>★ Thoughtful feedback</span><span>⌁ Sentiment awareness</span><span>◌ Quality signals</span></div></section><section className="auth-card"><div><p className="eyebrow">STORE RATING PLATFORM</p><h2>{title}</h2><p className="muted">{subtitle}</p></div>{children}</section></div>}
