import { useEffect, useState } from "react";
import { api } from "../api/client";
import { Loading, Notice } from "../components/Feedback";
import StarRating from "../components/StarRating";
import { Page } from "./Admin";
import type { Store } from "../types";
export function StoreList(){const [stores,setStores]=useState<Store[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [active,setActive]=useState<Store>();const load=async()=>{setLoading(true);try{const d=await api<{stores:Store[]}>(`/user/stores?name=${encodeURIComponent(query)}`);setStores(d.stores)}catch(e){setError(e instanceof Error?e.message:"Unable to load stores.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);if(loading)return <Loading/>;return <Page title="Find a store" subtitle="Your rating helps others choose with confidence."><div className="search-row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search by store name"/><button className="button secondary" onClick={load}>Search</button></div>{error&&<Notice message={error}/>}<div className="store-grid">{stores.map(store=><article className="store-card" key={store.id}><div><h3>{store.name}</h3><p>{store.address}</p></div><div className="store-score"><strong>★ {store.averageRating.toFixed(1)}</strong><span>{store.myRating ? `You gave ${store.myRating}/5` : "Not rated yet"}</span></div><button className="button secondary" onClick={()=>setActive(store)}>{store.myRating ? "Update rating" : "Rate this store"}</button></article>)}</div>{!stores.length&&<p className="empty">No stores match your search.</p>}{active&&<RatingModal store={active} onClose={()=>setActive(undefined)} onSaved={load}/>}</Page>}
function RatingModal({store,onClose,onSaved}:{store:Store;onClose:()=>void;onSaved:()=>void}){const [value,setValue]=useState(store.myRating||0);const [comment,setComment]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);const save=async()=>{if(!value){setError("Choose a star rating first.");return}setSaving(true);setError("");try{await api("/user/ratings",{method:"POST",body:JSON.stringify({storeId:store.id,value,comment:comment||undefined})});onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:"Unable to save rating.")}finally{setSaving(false)}};return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">YOUR FEEDBACK</p><h2>Rate {store.name}</h2><p className="muted">A short note helps sentiment analysis capture the context behind your rating.</p><StarRating value={value} onChange={setValue}/><label>Optional comment<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={500} placeholder="What stood out about your experience?"/></label>{error&&<Notice message={error}/>}<button className="button full" disabled={saving} onClick={save}>{saving?"Saving…":"Save rating"}</button></section></div>}
export function Account(){const [current,setCurrent]=useState("");const [next,setNext]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setMessage("");try{const d=await api<{message:string}>("/user/change-password",{method:"PUT",body:JSON.stringify({currentPassword:current,newPassword:next})});setMessage(d.message);setCurrent("");setNext("")}catch(err){setError(err instanceof Error?err.message:"Unable to change password.")}};return <Page title="Account security" subtitle="Keep your StorePulse account secure."><section className="form-panel narrow"><h3>Change password</h3><form onSubmit={submit}><label>Current password<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>New password <small>8–16 chars, uppercase + special character</small><input type="password" value={next} onChange={e=>setNext(e.target.value)} minLength={8} maxLength={16} required/></label>{error&&<Notice message={error}/>} {message&&<Notice type="success" message={message}/>}<button className="button">Update password</button></form></section></Page>}
